# Generated by Django 4.2.1 on 2023-07-02 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(default='', max_length=1000, null=True)),
                ('ingredientes', models.CharField(max_length=1000)),
                ('pasos', models.CharField(max_length=1000)),
                ('tiempo_de_coccion', models.IntegerField()),
                ('fecha_hora_de_subida', models.DateTimeField(default=datetime.datetime.now)),
                ('imagen', models.ImageField(blank=True, default='imagenes/default.jpg', null=True, upload_to='imagenes')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(related_name='recetas', to='AppRecetas.categoría')),
            ],
        ),
    ]
