# Generated by Django 4.2.1 on 2023-07-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes/default.jpg', null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='subtitulo',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
